window.ATG_CONFIG = {
  "competitionName": "Around the Grounds - FIFA World Cup 2026 Edition",
  "fifaSourceUrl": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures?country=US&wtw-filter=ALL",
  "firebase": {
    "enabled": true,
    "statePath": [
      "competitions",
      "worldcup2026"
    ],
    "auditCollection": [
      "competitions",
      "worldcup2026",
      "audit"
    ],
    "historyCollection": [
      "competitions",
      "worldcup2026",
      "history"
    ],
    "config": {
      "apiKey": "AIzaSyBzQRQIQ7gqRuFV_64oUMbApIQSRcnjcnk",
      "authDomain": "atg-world-cup-26.firebaseapp.com",
      "projectId": "atg-world-cup-26",
      "storageBucket": "atg-world-cup-26.firebasestorage.app",
      "messagingSenderId": "506347323919",
      "appId": "1:506347323919:web:e92bdd07905073797c597a"
    }
  },
  "passcodes": {
    "superAdmin": "ATG2026ADMIN",
    "regions": {
      "steve-josh": "SJ2026",
      "southeast": "SE2026",
      "texas": "TX2026",
      "midwest": "MW2026",
      "mid-atlantic": "MA2026"
    }
  },
  "regions": [
    {
      "id": "steve-josh",
      "name": "Steve & Josh",
      "members": [
        "Steve",
        "Josh"
      ]
    },
    {
      "id": "southeast",
      "name": "Southeast",
      "members": [
        "Justin",
        "Ashley",
        "Drake"
      ]
    },
    {
      "id": "texas",
      "name": "Texas",
      "members": [
        "Zarin",
        "Gabriella"
      ]
    },
    {
      "id": "midwest",
      "name": "Midwest",
      "members": [
        "Sean",
        "Andrew",
        "Sam"
      ]
    },
    {
      "id": "mid-atlantic",
      "name": "Mid-Atlantic",
      "members": [
        "John",
        "Skyler"
      ]
    }
  ],
  "matches": [
    {
      "id": "1",
      "matchNumber": 1,
      "date": "2026-06-11",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "13:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "Mexico",
      "away": "South Africa",
      "venue": "Estadio Azteca, Mexico City, Mexico",
      "city": "Mexico City",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "2",
      "matchNumber": 2,
      "date": "2026-06-11",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "Korea Republic",
      "away": "Czechia",
      "venue": "Estadio Akron, Guadalajara, Mexico",
      "city": "Guadalajara",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "3",
      "matchNumber": 3,
      "date": "2026-06-12",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Canada",
      "away": "Bosnia and Herzegovina",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "4",
      "matchNumber": 4,
      "date": "2026-06-12",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "United States",
      "away": "Paraguay",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "5",
      "matchNumber": 5,
      "date": "2026-06-13",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Haiti",
      "away": "Scotland",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "6",
      "matchNumber": 6,
      "date": "2026-06-13",
      "time": "00:00",
      "timeET": "00:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "Australia",
      "away": "T\u00fcrkiye",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "7",
      "matchNumber": 7,
      "date": "2026-06-13",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Brazil",
      "away": "Morocco",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "8",
      "matchNumber": 8,
      "date": "2026-06-13",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Qatar",
      "away": "Switzerland",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "9",
      "matchNumber": 9,
      "date": "2026-06-14",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "C\u00f4te d\u2019Ivoire",
      "away": "Ecuador",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "10",
      "matchNumber": 10,
      "date": "2026-06-14",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "Germany",
      "away": "Cura\u00e7ao",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "11",
      "matchNumber": 11,
      "date": "2026-06-14",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Netherlands",
      "away": "Japan",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "12",
      "matchNumber": 12,
      "date": "2026-06-14",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Sweden",
      "away": "Tunisia",
      "venue": "Estadio BBVA, Monterrey, Mexico",
      "city": "Monterrey",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "13",
      "matchNumber": 13,
      "date": "2026-06-15",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Saudi Arabia",
      "away": "Uruguay",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "14",
      "matchNumber": 14,
      "date": "2026-06-15",
      "time": "12:00",
      "timeET": "12:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Spain",
      "away": "Cabo Verde",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "15",
      "matchNumber": 15,
      "date": "2026-06-15",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "Iran",
      "away": "New Zealand",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "16",
      "matchNumber": 16,
      "date": "2026-06-15",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "Belgium",
      "away": "Egypt",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "17",
      "matchNumber": 17,
      "date": "2026-06-16",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "France",
      "away": "Senegal",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "18",
      "matchNumber": 18,
      "date": "2026-06-16",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "Iraq",
      "away": "Norway",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "19",
      "matchNumber": 19,
      "date": "2026-06-16",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Argentina",
      "away": "Algeria",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "20",
      "matchNumber": 20,
      "date": "2026-06-16",
      "time": "00:00",
      "timeET": "00:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Austria",
      "away": "Jordan",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "21",
      "matchNumber": 21,
      "date": "2026-06-17",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "Ghana",
      "away": "Panama",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "22",
      "matchNumber": 22,
      "date": "2026-06-17",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "England",
      "away": "Croatia",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "23",
      "matchNumber": 23,
      "date": "2026-06-17",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Portugal",
      "away": "Congo DR",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "24",
      "matchNumber": 24,
      "date": "2026-06-17",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Uzbekistan",
      "away": "Colombia",
      "venue": "Estadio Azteca, Mexico City, Mexico",
      "city": "Mexico City",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "25",
      "matchNumber": 25,
      "date": "2026-06-18",
      "time": "12:00",
      "timeET": "12:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "Czechia",
      "away": "South Africa",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "26",
      "matchNumber": 26,
      "date": "2026-06-18",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Switzerland",
      "away": "Bosnia and Herzegovina",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "27",
      "matchNumber": 27,
      "date": "2026-06-18",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Canada",
      "away": "Qatar",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "28",
      "matchNumber": 28,
      "date": "2026-06-18",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "Mexico",
      "away": "Korea Republic",
      "venue": "Estadio Akron, Guadalajara, Mexico",
      "city": "Guadalajara",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "29",
      "matchNumber": 29,
      "date": "2026-06-19",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Brazil",
      "away": "Haiti",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "30",
      "matchNumber": 30,
      "date": "2026-06-19",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Scotland",
      "away": "Morocco",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "31",
      "matchNumber": 31,
      "date": "2026-06-19",
      "time": "23:00",
      "timeET": "23:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "T\u00fcrkiye",
      "away": "Paraguay",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "32",
      "matchNumber": 32,
      "date": "2026-06-19",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "United States",
      "away": "Australia",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "33",
      "matchNumber": 33,
      "date": "2026-06-20",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "Germany",
      "away": "C\u00f4te d\u2019Ivoire",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "34",
      "matchNumber": 34,
      "date": "2026-06-20",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "Ecuador",
      "away": "Cura\u00e7ao",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "35",
      "matchNumber": 35,
      "date": "2026-06-20",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Netherlands",
      "away": "Sweden",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "36",
      "matchNumber": 36,
      "date": "2026-06-20",
      "time": "00:00",
      "timeET": "00:00",
      "timeLocal": "22:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Tunisia",
      "away": "Japan",
      "venue": "Estadio BBVA, Monterrey, Mexico",
      "city": "Monterrey",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "37",
      "matchNumber": 37,
      "date": "2026-06-21",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Uruguay",
      "away": "Cabo Verde",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "38",
      "matchNumber": 38,
      "date": "2026-06-21",
      "time": "12:00",
      "timeET": "12:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Spain",
      "away": "Saudi Arabia",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "39",
      "matchNumber": 39,
      "date": "2026-06-21",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "Belgium",
      "away": "Iran",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "40",
      "matchNumber": 40,
      "date": "2026-06-21",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "New Zealand",
      "away": "Egypt",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "41",
      "matchNumber": 41,
      "date": "2026-06-22",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "Norway",
      "away": "Senegal",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "42",
      "matchNumber": 42,
      "date": "2026-06-22",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "France",
      "away": "Iraq",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "43",
      "matchNumber": 43,
      "date": "2026-06-22",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Argentina",
      "away": "Austria",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "44",
      "matchNumber": 44,
      "date": "2026-06-22",
      "time": "23:00",
      "timeET": "23:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Jordan",
      "away": "Algeria",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "45",
      "matchNumber": 45,
      "date": "2026-06-23",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "England",
      "away": "Ghana",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "46",
      "matchNumber": 46,
      "date": "2026-06-23",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "Panama",
      "away": "Croatia",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "47",
      "matchNumber": 47,
      "date": "2026-06-23",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Portugal",
      "away": "Uzbekistan",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "48",
      "matchNumber": 48,
      "date": "2026-06-23",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Colombia",
      "away": "Congo DR",
      "venue": "Estadio Akron, Guadalajara, Mexico",
      "city": "Guadalajara",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "49",
      "matchNumber": 49,
      "date": "2026-06-24",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Scotland",
      "away": "Brazil",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "50",
      "matchNumber": 50,
      "date": "2026-06-24",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group C",
      "home": "Morocco",
      "away": "Haiti",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "51",
      "matchNumber": 51,
      "date": "2026-06-24",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Switzerland",
      "away": "Canada",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "52",
      "matchNumber": 52,
      "date": "2026-06-24",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group B",
      "home": "Bosnia and Herzegovina",
      "away": "Qatar",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "53",
      "matchNumber": 53,
      "date": "2026-06-24",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "Czechia",
      "away": "Mexico",
      "venue": "Estadio Azteca, Mexico City, Mexico",
      "city": "Mexico City",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "54",
      "matchNumber": 54,
      "date": "2026-06-24",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group A",
      "home": "South Africa",
      "away": "Korea Republic",
      "venue": "Estadio BBVA, Monterrey, Mexico",
      "city": "Monterrey",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "55",
      "matchNumber": 55,
      "date": "2026-06-25",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "Cura\u00e7ao",
      "away": "C\u00f4te d\u2019Ivoire",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "56",
      "matchNumber": 56,
      "date": "2026-06-25",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group E",
      "home": "Ecuador",
      "away": "Germany",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "57",
      "matchNumber": 57,
      "date": "2026-06-25",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Japan",
      "away": "Sweden",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "58",
      "matchNumber": 58,
      "date": "2026-06-25",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group F",
      "home": "Tunisia",
      "away": "Netherlands",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "59",
      "matchNumber": 59,
      "date": "2026-06-25",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "T\u00fcrkiye",
      "away": "United States",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "60",
      "matchNumber": 60,
      "date": "2026-06-25",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group D",
      "home": "Paraguay",
      "away": "Australia",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "61",
      "matchNumber": 61,
      "date": "2026-06-26",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "Norway",
      "away": "France",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "62",
      "matchNumber": 62,
      "date": "2026-06-26",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group I",
      "home": "Senegal",
      "away": "Iraq",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "63",
      "matchNumber": 63,
      "date": "2026-06-26",
      "time": "23:00",
      "timeET": "23:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "Egypt",
      "away": "Iran",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "64",
      "matchNumber": 64,
      "date": "2026-06-26",
      "time": "23:00",
      "timeET": "23:00",
      "timeLocal": "20:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group G",
      "home": "New Zealand",
      "away": "Belgium",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "65",
      "matchNumber": 65,
      "date": "2026-06-26",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "19:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Cabo Verde",
      "away": "Saudi Arabia",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "66",
      "matchNumber": 66,
      "date": "2026-06-26",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "18:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group H",
      "home": "Uruguay",
      "away": "Spain",
      "venue": "Estadio Akron, Guadalajara, Mexico",
      "city": "Guadalajara",
      "country": "Mexico",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "67",
      "matchNumber": 67,
      "date": "2026-06-27",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "Panama",
      "away": "England",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "68",
      "matchNumber": 68,
      "date": "2026-06-27",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group L",
      "home": "Croatia",
      "away": "Ghana",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "69",
      "matchNumber": 69,
      "date": "2026-06-27",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Algeria",
      "away": "Austria",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "70",
      "matchNumber": 70,
      "date": "2026-06-27",
      "time": "22:00",
      "timeET": "22:00",
      "timeLocal": "21:00",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group J",
      "home": "Jordan",
      "away": "Argentina",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "71",
      "matchNumber": 71,
      "date": "2026-06-27",
      "time": "19:30",
      "timeET": "19:30",
      "timeLocal": "19:30",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Colombia",
      "away": "Portugal",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "72",
      "matchNumber": 72,
      "date": "2026-06-27",
      "time": "19:30",
      "timeET": "19:30",
      "timeLocal": "19:30",
      "stage": "Group Stage",
      "stageType": "group",
      "stageLabel": "Group Stage",
      "group": "Group K",
      "home": "Congo DR",
      "away": "Uzbekistan",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "confirmed_group_fixture"
    },
    {
      "id": "73",
      "matchNumber": 73,
      "date": "2026-06-28",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group A Runner-up",
      "away": "Group B Runner-up",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "74",
      "matchNumber": 74,
      "date": "2026-06-29",
      "time": "16:30",
      "timeET": "16:30",
      "timeLocal": "16:30",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group E Winner",
      "away": "Group A/B/C/D/F 3rd Place",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "75",
      "matchNumber": 75,
      "date": "2026-06-29",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "19:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group F Winner",
      "away": "Group C Runner-up",
      "venue": "Estadio BBVA, Monterrey, Mexico",
      "city": "Monterrey",
      "country": "Mexico",
      "status": "bracket_slot"
    },
    {
      "id": "76",
      "matchNumber": 76,
      "date": "2026-06-29",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group C Winner",
      "away": "Group F Runner-up",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "77",
      "matchNumber": 77,
      "date": "2026-06-30",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group I Winner",
      "away": "Group C/D/F/G/H 3rd Place",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "78",
      "matchNumber": 78,
      "date": "2026-06-30",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group E Runner-up",
      "away": "Group I Runner-up",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "79",
      "matchNumber": 79,
      "date": "2026-06-30",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "19:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group A Winner",
      "away": "Group C/E/F/H/I 3rd Place",
      "venue": "Estadio Azteca, Mexico City, Mexico",
      "city": "Mexico City",
      "country": "Mexico",
      "status": "bracket_slot"
    },
    {
      "id": "80",
      "matchNumber": 80,
      "date": "2026-07-01",
      "time": "12:00",
      "timeET": "12:00",
      "timeLocal": "12:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group L Winner",
      "away": "Group E/H/I/J/K 3rd Place",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "81",
      "matchNumber": 81,
      "date": "2026-07-01",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "17:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group D Winner",
      "away": "Group B/E/F/I/J 3rd Place",
      "venue": "Levi's Stadium, San Francisco Bay Area, United States",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "82",
      "matchNumber": 82,
      "date": "2026-07-01",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "13:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group G Winner",
      "away": "Group A/E/H/I/J 3rd Place",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "83",
      "matchNumber": 83,
      "date": "2026-07-02",
      "time": "19:00",
      "timeET": "19:00",
      "timeLocal": "19:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group K Runner-up",
      "away": "Group L Runner-up",
      "venue": "BMO Field, Toronto, Canada",
      "city": "Toronto",
      "country": "Canada",
      "status": "bracket_slot"
    },
    {
      "id": "84",
      "matchNumber": 84,
      "date": "2026-07-02",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group H Winner",
      "away": "Group J Runner-up",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "85",
      "matchNumber": 85,
      "date": "2026-07-02",
      "time": "23:00",
      "timeET": "23:00",
      "timeLocal": "20:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group B Winner",
      "away": "Group E/F/G/I/J 3rd Place",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "bracket_slot"
    },
    {
      "id": "86",
      "matchNumber": 86,
      "date": "2026-07-03",
      "time": "18:00",
      "timeET": "18:00",
      "timeLocal": "18:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group J Winner",
      "away": "Group H Runner-up",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "87",
      "matchNumber": 87,
      "date": "2026-07-03",
      "time": "21:30",
      "timeET": "21:30",
      "timeLocal": "20:30",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group K Winner",
      "away": "Group D/E/I/J/L 3rd Place",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "88",
      "matchNumber": 88,
      "date": "2026-07-03",
      "time": "14:00",
      "timeET": "14:00",
      "timeLocal": "13:00",
      "stage": "Round of 32",
      "stageType": "knockout",
      "stageLabel": "Round of 32",
      "group": "Round of 32",
      "home": "Group D Runner-up",
      "away": "Group G Runner-up",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "89",
      "matchNumber": 89,
      "date": "2026-07-04",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 74 Winner",
      "away": "Match 77 Winner",
      "venue": "Lincoln Financial Field, Philadelphia, United States",
      "city": "Philadelphia",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "90",
      "matchNumber": 90,
      "date": "2026-07-04",
      "time": "13:00",
      "timeET": "13:00",
      "timeLocal": "12:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 73 Winner",
      "away": "Match 75 Winner",
      "venue": "NRG Stadium, Houston, United States",
      "city": "Houston",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "91",
      "matchNumber": 91,
      "date": "2026-07-05",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 76 Winner",
      "away": "Match 78 Winner",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "92",
      "matchNumber": 92,
      "date": "2026-07-05",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "18:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 79 Winner",
      "away": "Match 80 Winner",
      "venue": "Estadio Azteca, Mexico City, Mexico",
      "city": "Mexico City",
      "country": "Mexico",
      "status": "bracket_slot"
    },
    {
      "id": "93",
      "matchNumber": 93,
      "date": "2026-07-06",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "14:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 83 Winner",
      "away": "Match 84 Winner",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "94",
      "matchNumber": 94,
      "date": "2026-07-06",
      "time": "20:00",
      "timeET": "20:00",
      "timeLocal": "17:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 81 Winner",
      "away": "Match 82 Winner",
      "venue": "Lumen Field, Seattle, United States",
      "city": "Seattle",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "95",
      "matchNumber": 95,
      "date": "2026-07-07",
      "time": "12:00",
      "timeET": "12:00",
      "timeLocal": "12:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 86 Winner",
      "away": "Match 88 Winner",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "96",
      "matchNumber": 96,
      "date": "2026-07-07",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "13:00",
      "stage": "Round of 16",
      "stageType": "knockout",
      "stageLabel": "Round of 16",
      "group": "Round of 16",
      "home": "Match 85 Winner",
      "away": "Match 87 Winner",
      "venue": "BC Place, Vancouver, Canada",
      "city": "Vancouver",
      "country": "Canada",
      "status": "bracket_slot"
    },
    {
      "id": "97",
      "matchNumber": 97,
      "date": "2026-07-09",
      "time": "16:00",
      "timeET": "16:00",
      "timeLocal": "16:00",
      "stage": "Quarter-finals",
      "stageType": "knockout",
      "stageLabel": "Quarter-finals",
      "group": "Quarter-finals",
      "home": "Match 89 Winner",
      "away": "Match 90 Winner",
      "venue": "Gillette Stadium, Boston, United States",
      "city": "Boston",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "98",
      "matchNumber": 98,
      "date": "2026-07-10",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "12:00",
      "stage": "Quarter-finals",
      "stageType": "knockout",
      "stageLabel": "Quarter-finals",
      "group": "Quarter-finals",
      "home": "Match 93 Winner",
      "away": "Match 94 Winner",
      "venue": "SoFi Stadium, Los Angeles, United States",
      "city": "Los Angeles",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "99",
      "matchNumber": 99,
      "date": "2026-07-11",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Quarter-finals",
      "stageType": "knockout",
      "stageLabel": "Quarter-finals",
      "group": "Quarter-finals",
      "home": "Match 91 Winner",
      "away": "Match 92 Winner",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "100",
      "matchNumber": 100,
      "date": "2026-07-11",
      "time": "21:00",
      "timeET": "21:00",
      "timeLocal": "20:00",
      "stage": "Quarter-finals",
      "stageType": "knockout",
      "stageLabel": "Quarter-finals",
      "group": "Quarter-finals",
      "home": "Match 95 Winner",
      "away": "Match 96 Winner",
      "venue": "Arrowhead Stadium, Kansas City, United States",
      "city": "Kansas City",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "101",
      "matchNumber": 101,
      "date": "2026-07-14",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "14:00",
      "stage": "Semi-finals",
      "stageType": "knockout",
      "stageLabel": "Semi-finals",
      "group": "Semi-finals",
      "home": "Match 97 Winner",
      "away": "Match 98 Winner",
      "venue": "AT&T Stadium, Dallas, United States",
      "city": "Dallas",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "102",
      "matchNumber": 102,
      "date": "2026-07-15",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Semi-finals",
      "stageType": "knockout",
      "stageLabel": "Semi-finals",
      "group": "Semi-finals",
      "home": "Match 99 Winner",
      "away": "Match 100 Winner",
      "venue": "Mercedes-Benz Stadium, Atlanta, United States",
      "city": "Atlanta",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "103",
      "matchNumber": 103,
      "date": "2026-07-18",
      "time": "17:00",
      "timeET": "17:00",
      "timeLocal": "17:00",
      "stage": "Third Place",
      "stageType": "knockout",
      "stageLabel": "Third Place",
      "group": "Third Place",
      "home": "Match 101 Loser",
      "away": "Match 102 Loser",
      "venue": "Hard Rock Stadium, Miami, United States",
      "city": "Miami",
      "country": "United States",
      "status": "bracket_slot"
    },
    {
      "id": "104",
      "matchNumber": 104,
      "date": "2026-07-19",
      "time": "15:00",
      "timeET": "15:00",
      "timeLocal": "15:00",
      "stage": "Final",
      "stageType": "knockout",
      "stageLabel": "Final",
      "group": "Final",
      "home": "Match 101 Winner",
      "away": "Match 102 Winner",
      "venue": "MetLife Stadium, New York/New Jersey, United States",
      "city": "New York/New Jersey",
      "country": "United States",
      "status": "bracket_slot"
    }
  ]
};
