window.ATG_SCHEDULE = [
  {
    "id": "1",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-11",
    "timeET": "15:00",
    "homeTeam": "Mexico",
    "awayTeam": "South Africa",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "2",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-11",
    "timeET": "22:00",
    "homeTeam": "Korea Republic",
    "awayTeam": "Czechia",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "3",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-12",
    "timeET": "15:00",
    "homeTeam": "Canada",
    "awayTeam": "Bosnia and Herzegovina",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "4",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-12",
    "timeET": "21:00",
    "homeTeam": "United States",
    "awayTeam": "Paraguay",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "5",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-13",
    "timeET": "21:00",
    "homeTeam": "Haiti",
    "awayTeam": "Scotland",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "6",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-13",
    "timeET": "00:00",
    "homeTeam": "Australia",
    "awayTeam": "Türkiye",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "7",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-13",
    "timeET": "18:00",
    "homeTeam": "Brazil",
    "awayTeam": "Morocco",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "8",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-13",
    "timeET": "15:00",
    "homeTeam": "Qatar",
    "awayTeam": "Switzerland",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "9",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-14",
    "timeET": "19:00",
    "homeTeam": "Côte d’Ivoire",
    "awayTeam": "Ecuador",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "10",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-14",
    "timeET": "13:00",
    "homeTeam": "Germany",
    "awayTeam": "Curaçao",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "11",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-14",
    "timeET": "16:00",
    "homeTeam": "Netherlands",
    "awayTeam": "Japan",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "12",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-14",
    "timeET": "22:00",
    "homeTeam": "Sweden",
    "awayTeam": "Tunisia",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "13",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-15",
    "timeET": "18:00",
    "homeTeam": "Saudi Arabia",
    "awayTeam": "Uruguay",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "14",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-15",
    "timeET": "12:00",
    "homeTeam": "Spain",
    "awayTeam": "Cabo Verde",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "15",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-15",
    "timeET": "21:00",
    "homeTeam": "Iran",
    "awayTeam": "New Zealand",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "16",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-15",
    "timeET": "15:00",
    "homeTeam": "Belgium",
    "awayTeam": "Egypt",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "17",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-16",
    "timeET": "15:00",
    "homeTeam": "France",
    "awayTeam": "Senegal",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "18",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-16",
    "timeET": "18:00",
    "homeTeam": "Iraq",
    "awayTeam": "Norway",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "19",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-16",
    "timeET": "21:00",
    "homeTeam": "Argentina",
    "awayTeam": "Algeria",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "20",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-16",
    "timeET": "00:00",
    "homeTeam": "Austria",
    "awayTeam": "Jordan",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "21",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-17",
    "timeET": "19:00",
    "homeTeam": "Ghana",
    "awayTeam": "Panama",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "22",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-17",
    "timeET": "16:00",
    "homeTeam": "England",
    "awayTeam": "Croatia",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "23",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-17",
    "timeET": "13:00",
    "homeTeam": "Portugal",
    "awayTeam": "Congo DR",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "24",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-17",
    "timeET": "22:00",
    "homeTeam": "Uzbekistan",
    "awayTeam": "Colombia",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "25",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-18",
    "timeET": "12:00",
    "homeTeam": "Czechia",
    "awayTeam": "South Africa",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "26",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-18",
    "timeET": "15:00",
    "homeTeam": "Switzerland",
    "awayTeam": "Bosnia and Herzegovina",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "27",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-18",
    "timeET": "18:00",
    "homeTeam": "Canada",
    "awayTeam": "Qatar",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "28",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-18",
    "timeET": "21:00",
    "homeTeam": "Mexico",
    "awayTeam": "Korea Republic",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "29",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-19",
    "timeET": "21:00",
    "homeTeam": "Brazil",
    "awayTeam": "Haiti",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "30",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-19",
    "timeET": "18:00",
    "homeTeam": "Scotland",
    "awayTeam": "Morocco",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "31",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-19",
    "timeET": "23:00",
    "homeTeam": "Türkiye",
    "awayTeam": "Paraguay",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "32",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-19",
    "timeET": "15:00",
    "homeTeam": "United States",
    "awayTeam": "Australia",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "33",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-20",
    "timeET": "16:00",
    "homeTeam": "Germany",
    "awayTeam": "Côte d’Ivoire",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "34",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-20",
    "timeET": "20:00",
    "homeTeam": "Ecuador",
    "awayTeam": "Curaçao",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "35",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-20",
    "timeET": "13:00",
    "homeTeam": "Netherlands",
    "awayTeam": "Sweden",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "36",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-20",
    "timeET": "00:00",
    "homeTeam": "Tunisia",
    "awayTeam": "Japan",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "37",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-21",
    "timeET": "18:00",
    "homeTeam": "Uruguay",
    "awayTeam": "Cabo Verde",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "38",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-21",
    "timeET": "12:00",
    "homeTeam": "Spain",
    "awayTeam": "Saudi Arabia",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "39",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-21",
    "timeET": "15:00",
    "homeTeam": "Belgium",
    "awayTeam": "Iran",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "40",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-21",
    "timeET": "21:00",
    "homeTeam": "New Zealand",
    "awayTeam": "Egypt",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "41",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-22",
    "timeET": "20:00",
    "homeTeam": "Norway",
    "awayTeam": "Senegal",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "42",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-22",
    "timeET": "17:00",
    "homeTeam": "France",
    "awayTeam": "Iraq",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "43",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-22",
    "timeET": "13:00",
    "homeTeam": "Argentina",
    "awayTeam": "Austria",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "44",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-22",
    "timeET": "23:00",
    "homeTeam": "Jordan",
    "awayTeam": "Algeria",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "45",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-23",
    "timeET": "16:00",
    "homeTeam": "England",
    "awayTeam": "Ghana",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "46",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-23",
    "timeET": "19:00",
    "homeTeam": "Panama",
    "awayTeam": "Croatia",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "47",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-23",
    "timeET": "13:00",
    "homeTeam": "Portugal",
    "awayTeam": "Uzbekistan",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "48",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-23",
    "timeET": "22:00",
    "homeTeam": "Colombia",
    "awayTeam": "Congo DR",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "49",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-24",
    "timeET": "18:00",
    "homeTeam": "Scotland",
    "awayTeam": "Brazil",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "50",
    "stage": "Group Stage",
    "group": "C",
    "date": "2026-06-24",
    "timeET": "18:00",
    "homeTeam": "Morocco",
    "awayTeam": "Haiti",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "51",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-24",
    "timeET": "15:00",
    "homeTeam": "Switzerland",
    "awayTeam": "Canada",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "52",
    "stage": "Group Stage",
    "group": "B",
    "date": "2026-06-24",
    "timeET": "15:00",
    "homeTeam": "Bosnia and Herzegovina",
    "awayTeam": "Qatar",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "53",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-24",
    "timeET": "21:00",
    "homeTeam": "Czechia",
    "awayTeam": "Mexico",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "54",
    "stage": "Group Stage",
    "group": "A",
    "date": "2026-06-24",
    "timeET": "21:00",
    "homeTeam": "South Africa",
    "awayTeam": "Korea Republic",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "55",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-25",
    "timeET": "16:00",
    "homeTeam": "Curaçao",
    "awayTeam": "Côte d’Ivoire",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "56",
    "stage": "Group Stage",
    "group": "E",
    "date": "2026-06-25",
    "timeET": "16:00",
    "homeTeam": "Ecuador",
    "awayTeam": "Germany",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "57",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-25",
    "timeET": "19:00",
    "homeTeam": "Japan",
    "awayTeam": "Sweden",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "58",
    "stage": "Group Stage",
    "group": "F",
    "date": "2026-06-25",
    "timeET": "19:00",
    "homeTeam": "Tunisia",
    "awayTeam": "Netherlands",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "59",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-25",
    "timeET": "22:00",
    "homeTeam": "Türkiye",
    "awayTeam": "United States",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "60",
    "stage": "Group Stage",
    "group": "D",
    "date": "2026-06-25",
    "timeET": "22:00",
    "homeTeam": "Paraguay",
    "awayTeam": "Australia",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "61",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-26",
    "timeET": "15:00",
    "homeTeam": "Norway",
    "awayTeam": "France",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "62",
    "stage": "Group Stage",
    "group": "I",
    "date": "2026-06-26",
    "timeET": "15:00",
    "homeTeam": "Senegal",
    "awayTeam": "Iraq",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "63",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-26",
    "timeET": "23:00",
    "homeTeam": "Egypt",
    "awayTeam": "Iran",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "64",
    "stage": "Group Stage",
    "group": "G",
    "date": "2026-06-26",
    "timeET": "23:00",
    "homeTeam": "New Zealand",
    "awayTeam": "Belgium",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "65",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-26",
    "timeET": "20:00",
    "homeTeam": "Cabo Verde",
    "awayTeam": "Saudi Arabia",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "66",
    "stage": "Group Stage",
    "group": "H",
    "date": "2026-06-26",
    "timeET": "20:00",
    "homeTeam": "Uruguay",
    "awayTeam": "Spain",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "67",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-27",
    "timeET": "17:00",
    "homeTeam": "Panama",
    "awayTeam": "England",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "68",
    "stage": "Group Stage",
    "group": "L",
    "date": "2026-06-27",
    "timeET": "17:00",
    "homeTeam": "Croatia",
    "awayTeam": "Ghana",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "69",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-27",
    "timeET": "22:00",
    "homeTeam": "Algeria",
    "awayTeam": "Austria",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "70",
    "stage": "Group Stage",
    "group": "J",
    "date": "2026-06-27",
    "timeET": "22:00",
    "homeTeam": "Jordan",
    "awayTeam": "Argentina",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "71",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-27",
    "timeET": "19:30",
    "homeTeam": "Colombia",
    "awayTeam": "Portugal",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "72",
    "stage": "Group Stage",
    "group": "K",
    "date": "2026-06-27",
    "timeET": "19:30",
    "homeTeam": "Congo DR",
    "awayTeam": "Uzbekistan",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "confirmed_group_fixture",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "73",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-28",
    "timeET": "15:00",
    "homeTeam": "Group A Runner-up",
    "awayTeam": "Group B Runner-up",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "74",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-29",
    "timeET": "16:30",
    "homeTeam": "Group E Winner",
    "awayTeam": "Highest 3rd Place A/B/C/D/F",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "75",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-29",
    "timeET": "21:00",
    "homeTeam": "Group F Winner",
    "awayTeam": "Group C Runner-up",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "76",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-29",
    "timeET": "13:00",
    "homeTeam": "Group C Winner",
    "awayTeam": "Group F Runner-up",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "77",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-30",
    "timeET": "17:00",
    "homeTeam": "Group I Winner",
    "awayTeam": "Highest 3rd Place C/D/F/G/H",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "78",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-30",
    "timeET": "13:00",
    "homeTeam": "Group E Runner-up",
    "awayTeam": "Group I Runner-up",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "79",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-06-30",
    "timeET": "21:00",
    "homeTeam": "Group A Winner",
    "awayTeam": "Highest 3rd Place C/E/F/H/I",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "80",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-01",
    "timeET": "12:00",
    "homeTeam": "Group L Winner",
    "awayTeam": "Highest 3rd Place E/H/I/J/K",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "81",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-01",
    "timeET": "20:00",
    "homeTeam": "Group D Winner",
    "awayTeam": "Highest 3rd Place B/E/F/I/J",
    "venue": "Levi's Stadium",
    "city": "San Francisco Bay Area",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "82",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-01",
    "timeET": "16:00",
    "homeTeam": "Group G Winner",
    "awayTeam": "Highest 3rd Place A/E/H/I/J",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "83",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-02",
    "timeET": "19:00",
    "homeTeam": "Group K Runner-up",
    "awayTeam": "Group L Runner-up",
    "venue": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "84",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-02",
    "timeET": "15:00",
    "homeTeam": "Group H Winner",
    "awayTeam": "Group J Runner-up",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "85",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-02",
    "timeET": "23:00",
    "homeTeam": "Group B Winner",
    "awayTeam": "Highest 3rd Place E/F/G/I/J",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "86",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-03",
    "timeET": "18:00",
    "homeTeam": "Group J Winner",
    "awayTeam": "Group H Runner-up",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "87",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-03",
    "timeET": "21:30",
    "homeTeam": "Group K Winner",
    "awayTeam": "Highest 3rd Place D/E/I/J/L",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "88",
    "stage": "Round of 32",
    "group": "",
    "date": "2026-07-03",
    "timeET": "14:00",
    "homeTeam": "Group D Runner-up",
    "awayTeam": "Group G Runner-up",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "89",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-04",
    "timeET": "17:00",
    "homeTeam": "Match 74 Winner",
    "awayTeam": "Match 77 Winner",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "90",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-04",
    "timeET": "13:00",
    "homeTeam": "Match 73 Winner",
    "awayTeam": "Match 75 Winner",
    "venue": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "91",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-05",
    "timeET": "16:00",
    "homeTeam": "Match 76 Winner",
    "awayTeam": "Match 78 Winner",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "92",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-05",
    "timeET": "20:00",
    "homeTeam": "Match 79 Winner",
    "awayTeam": "Match 80 Winner",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "93",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-06",
    "timeET": "15:00",
    "homeTeam": "Match 83 Winner",
    "awayTeam": "Match 84 Winner",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "94",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-06",
    "timeET": "20:00",
    "homeTeam": "Match 81 Winner",
    "awayTeam": "Match 82 Winner",
    "venue": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "95",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-07",
    "timeET": "12:00",
    "homeTeam": "Match 86 Winner",
    "awayTeam": "Match 88 Winner",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "96",
    "stage": "Round of 16",
    "group": "",
    "date": "2026-07-07",
    "timeET": "16:00",
    "homeTeam": "Match 85 Winner",
    "awayTeam": "Match 87 Winner",
    "venue": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "97",
    "stage": "Quarter-finals",
    "group": "",
    "date": "2026-07-09",
    "timeET": "16:00",
    "homeTeam": "Match 89 Winner",
    "awayTeam": "Match 90 Winner",
    "venue": "Gillette Stadium",
    "city": "Boston",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "98",
    "stage": "Quarter-finals",
    "group": "",
    "date": "2026-07-10",
    "timeET": "15:00",
    "homeTeam": "Match 93 Winner",
    "awayTeam": "Match 94 Winner",
    "venue": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "99",
    "stage": "Quarter-finals",
    "group": "",
    "date": "2026-07-11",
    "timeET": "17:00",
    "homeTeam": "Match 91 Winner",
    "awayTeam": "Match 92 Winner",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "100",
    "stage": "Quarter-finals",
    "group": "",
    "date": "2026-07-11",
    "timeET": "21:00",
    "homeTeam": "Match 95 Winner",
    "awayTeam": "Match 96 Winner",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "101",
    "stage": "Semi-finals",
    "group": "",
    "date": "2026-07-14",
    "timeET": "15:00",
    "homeTeam": "Match 97 Winner",
    "awayTeam": "Match 98 Winner",
    "venue": "AT&T Stadium",
    "city": "Dallas",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "102",
    "stage": "Semi-finals",
    "group": "",
    "date": "2026-07-15",
    "timeET": "15:00",
    "homeTeam": "Match 99 Winner",
    "awayTeam": "Match 100 Winner",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "103",
    "stage": "Third Place",
    "group": "",
    "date": "2026-07-18",
    "timeET": "17:00",
    "homeTeam": "Match 101 Loser",
    "awayTeam": "Match 102 Loser",
    "venue": "Hard Rock Stadium",
    "city": "Miami",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  },
  {
    "id": "104",
    "stage": "Final",
    "group": "",
    "date": "2026-07-19",
    "timeET": "15:00",
    "homeTeam": "Match 101 Winner",
    "awayTeam": "Match 102 Winner",
    "venue": "MetLife Stadium",
    "city": "New York/New Jersey",
    "country": "United States",
    "status": "bracket_slot",
    "homeScore": null,
    "awayScore": null
  }
];
